language: php

php:
  - 5.6
  - 7.0

before_script:
#  - travis_retry composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

notifications:
    slack:
        rooms:
            - sonntagnacht:CZvguyxyM0tlb6Smj7amHjTw#internetz
