language: php

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    - $HOME/.ccache
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  
before_install:
    # determine INI file
    - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then export INI=/etc/hhvm/php.ini; else export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
    # disable xdebug if available
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    # disable default memory limit
    - echo memory_limit = -1 >> $INI

before_script:
#  - travis_retry composer self-update
  - composer update --no-progress --no-suggest --ansi

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

notifications:
    slack:
        rooms:
            - sonntagnacht:CZvguyxyM0tlb6Smj7amHjTw#internetz
